apiVersion: v1
kind: Pod
metadata:
  name: consumer
spec:
  containers:
  - name: rmq-consumer
    image: rmq-app:v1
    args:
    - sh
    - -c
    - /app/receiver
    env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: rmq-secrets
            key: rmq_user
      - name: RABBITMQ_PASS
        valueFrom:
          secretKeyRef:
            name: rmq-secrets
            key: rmq_pass
      - name: RABBITMQ_HOST
        valueFrom:
          configMapKeyRef:
            name: rmq-configs
            key: rmq_host
      - name: RABBITMQ_PORT
        valueFrom:
          configMapKeyRef:
            name: rmq-configs
            key: rmq_port
  restartPolicy: OnFailure